from pydantic import BaseModel, Field, EmailStr


class UserLoginSchema(BaseModel):
    email: EmailStr = Field(...)
    password: str = Field(...)

    class Config:  # configuration for documentation generated by fastapi
        schema_extra = {
            "example": {"email": "sp@gmail.com", "password": "strong_password"}
        }
